version: '3'

services:

  mariadb:
    image: mariadb

    hostname: mariadb
    ports:
      - 3306:3306

    restart: always

    environment:
      - MARIADB_DATABASE=sites_man_db
      - MARIADB_ROOT_PASSWORD=root 
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass

    volumes:
      - mariadb-volume:/var/lib/mysql/
      
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    
    hostname: api
    ports:
      - 8070:8070
    
    depends_on:
      - mariadb
    
    restart: always
    
    environment:
      - MARIADB_DATABASE=sites_man_db
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass 
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - IDP_SERVER_URL=secret_url
      - IDP_CLIENT_ID=sites-man-api
      - IDP_CLIENT_SECRET=secret
      - IDP_ADMIN_CLIENT_SECRET=secret
      - IDP_REALM=g5-securitas
      - IDP_CALLBACK_URI=secret_url

      
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8070 --reload"
    volumes:
      - ./:/usr/app:ro

volumes:
  mariadb-volume:

networks:
  default:
    name: kc-api-bridge
    external: true