version: '3'

services:
  mariadb:
    image: mariadb

    hostname: db
    ports:
      - 3306:3306

    restart: always

    environment:
      - MARIADB_DATABASE=intrusion_man_db
      - MARIADB_ROOT_PASSWORD=root 
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass

    volumes:
      - mariadb-volume:/var/lib/mysql/
      
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    
    hostname: api
    ports:
      - 8000:8000
    
    depends_on:
      - mariadb
    
    restart: always
    
    environment:
      - MARIADB_DATABASE=intrusion_man_db
      - MARIADB_USER=dev_user
      - MARIADB_PASSWORD=dev_pass 
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  mariadb-volume: