name: Sites Management API testing

on:
  push:
    paths:
      - sitesManagementAPI/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
  pull_request:
    paths:
      - sitesManagementAPI/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
jobs:
  run_tests:
    name: Run management API tests
    runs-on: ubuntu-latest
    container: python:3.10
    
    env:
      MARIADB_USER: dev_user
      MARIADB_PASSWORD: dev_pass 
      MARIADB_DATABASE: sites_man_db
      MARIADB_HOST: db
      MARIADB_PORT: 3306
    
    services:
      db:
        image: mariadb
        env:
          MYSQL_USER: dev_user
          MYSQL_PASSWORD: dev_pass
          MYSQL_DATABASE: sites_man_db
          MYSQL_ROOT_PASSWORD: root
            
        ports:
          - 3306  
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5


    defaults:
      run:
        working-directory: ./sitesManagementAPI

    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: PYTHONPATH=${PYTHONPATH}:./src python -m pytest