name: Sites Management API Coverage and Testing

on:
  push:
    paths:
      - '.github/workflows/sites-management-api.yaml'
      - sitesManagementAPI/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
  pull_request:
    paths:
      - sitesManagementAPI/**
      - '!**.md'
      - '!**.pdf'
      - '!**.docx'
      - '!**.gitignore'
      - '!**.txt'
jobs:
  run_tests:
    name: Run management API tests
    runs-on: ubuntu-latest
    
    container: python:3.10
    
    # job env variables
    env:
      MARIADB_USER: dev_user
      MARIADB_PASSWORD: dev_pass 
      MARIADB_DATABASE: sites_man_db
      MARIADB_HOST: db
      MARIADB_PORT: 3306
    
    services:
      db:
        image: mariadb
        
        # container env variables
        env:
          MYSQL_USER: dev_user
          MYSQL_PASSWORD: dev_pass
          MYSQL_DATABASE: sites_man_db
          MYSQL_ROOT_PASSWORD: root
            
        ports:
          - 3306  
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5


    defaults:
      run:
        working-directory: ./sitesManagementAPI

    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tox and any other packages
        run: |
          pip install tox

      - name: Run tox
        run: tox -e py   

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SITES_MANAGEMENT_API }}
